kafka:
  bootstrap_servers:
    - "localhost:9092"
  topics:
    trade: "market.info"
    orderbook: "market.info"
    ohlcv: "market.ohlcv"
    liquidation: "market.info"
    open_interest: "market.info"
    funding_rate: "market.info"

influxdb:
  url: "http://localhost:8086"
  token: "my-secret-token"
  org: "my-org"
  bucket: "test-bucket"

exchanges:
  - name: "binance"
    symbols:
      - "BTC/USDT"
#      - "ETH/USDT"
    data_types:
#      - "trade"
#      - "orderbook"
#      - "ohlcv"
      - "liquidation"
      - "open_interest"
      - "funding_rate"
  - name: "okx"
    symbols:
      - "BTC"
    data_types:
      - "liquidation"
#      - "trade"
#      - "orderbook"